project_id = "fosvwmuvanqdwlqtlhlx"

[functions.agent-chat]
verify_jwt = false

[functions.ai-edit-image]
verify_jwt = false

[functions.ai-enhance-prompt]
verify_jwt = false

[functions.ai-remove-background]
verify_jwt = false

[functions.ai-select-model]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.liblib-generate]
verify_jwt = false

[functions.liblib-model-info]
verify_jwt = false
